### ISSUE TITLE
Thunderbird blocks 3rd party includes in the newsletter design

### ISSUE THREAD

**Issue by vsund** [blockstack/designs#208]
When opening the Blockstack newsletter with (I guess) Thunderbird's default settings, it blocks 3rd party resources and shows "we protected your privacy" and asks whether the user wants to allow 3rd party includes.

This results in looking like this: https://i.imgur.com/blF5rsQ.png
instead of this: https://i.imgur.com/3DGMrpH.png

**Comment by guylepage3** [comment]
Thanks @vsund we should have a fallback default for Thunderbird users. Cheers. 👍

**Comment by guylepage3** [comment]
resolved with [#245: redesign newsletter to be more platform friendly](https://github.com/blockstack/designs/issues/245)

**Comment by vsund** [comment]
Still have problems with the icons at the bottom :/

![screen](https://cloud.githubusercontent.com/assets/10466835/26725231/d9f5003a-479d-11e7-8273-8e38f766c824.png)

**Comment by pstan26** [comment]
darn,  cc'ing @guylepage3

**Comment by guylepage3** [comment]
yeah. again... Thunderbird is NOT supported by MailChimp. It's the 1% of usage for email clients. We cannot support it. Sorry @vsund. cc: @pstan26
